# Generated by Django 4.2.6 on 2023-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="logo.png", upload_to="profile_images"),
        ),
    ]
